### ISSUE TITLE
[課題1] 長いパスを指定すると動作を停止する

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#1]
こんにちは。FFRI基礎技術研究室の茂木です。
レビューをした結果をissueに立てていきますのでご対応お願いいたします。

環境:Windows 10
再現率:2/2
症状:ビルド後以下のように長いパスを入れ実行すると動作を停止する。
```
Ex1.exe aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
今回は課題ですので、何文字でエラー表示をすべきかについても調査を行い、動作を停止しないようにしてください。

**Comment by mrrsh** [comment]
インターン生の森です。レビューありがとうございます。
こちらの環境では202文字までのパス長まで使用できたため、パス長を202文字までに制限しました。
確認お願いします。
また、こちらの都合により課題1以外の修正対応が遅れます。

**Comment by ffriyukimogi** [comment]
別のディレクトリに実行ファイルを置いて実行するとどうでしょうか
例えばC直下だと203文字でもエラーなしで実行できませんか

**Comment by mrrsh** [comment]
失礼しました。調べましたところ、
「C:\」で244文字
「C:\Users\」で238文字
「C:\Users\user\Documents\GitHub\internship\solution\x64\Debug\」で186文字までと、受付けパス長が変化しました。実行ファイルのディレクトリのパスが一文字増えると、受付けできるパスが一文字減ったので、そのように変更しました。確認お願いします。

**Comment by ffriyukimogi** [comment]
ファイル作成する/しないの挙動はOKです
一方でパスが長すぎる場合に何かしらのエラーメッセージの表示がされると良いです
実際mkdirでは「ファイル名または拡張子が長すぎます。」とエラーメッセージが出ます

**Comment by mrrsh** [comment]
main関数のcontinueの前に、メッセージを出すように変更しました。確認お願いします。

**Comment by ffriyukimogi** [comment]
確認しました。OKです。closeします。
