### ISSUE TITLE
[課題1--5共通] コンパイラの警告と警告レベル

### ISSUE THREAD

**Issue by kohnakagawa-ffri** [mrrsh/internship#10]
すべての課題に共通ですが、コンパイラの警告レベルが `/W3` となっているので、`/W4` への変更をお願いします。

**Comment by ffriyukimogi** [comment]
Debug x64だと警告4になってますね。
できれば、プロパティの「すべての構成」で設定していただけると助かりますが、本課題としては特に問題はないので優先度は低めです。

**Comment by mrrsh** [comment]
失礼しました。変更できたと思いますので、ご確認お願いします。

**Comment by kohnakagawa-ffri** [comment]
ご対応ありがとうございます。すべての構成 x64 の組み合わせで警告レベルが全て `/W 4` になっていることを確認しました。
