### ISSUE TITLE
[課題3,5] _CRT_SECURE_NO_WARNINGS を定義し

### ISSUE THREAD

**Issue by kohnakagawa-ffri** [mrrsh/internship#11]
https://github.com/mrrsh/internship/blob/969c7f684765a6887b7426e213ddfc3359e90f98/solution/Ex3/netaof.cpp#L2

https://github.com/mrrsh/internship/blob/969c7f684765a6887b7426e213ddfc3359e90f98/solution/Ex5/union.cpp#L1

のように `_CRT_SECURE_NO_WARNINGS` を定義して、強引に  `strcpy` を使っていますが、MSがバッファオーバーランを防ぐ意図で用意している `strcpy_s` などを利用するようにしましょう。

（それか、C++の `std::string` (wide文字列版の `std::wstring`) を利用するのをおすすめします。）

**Comment by kohnakagawa-ffri** [comment]
イシューの書き方が悪くすみません。今回のイシューの意図は「 `_CRT_SECURE_NO_WARNINGS` のようなマクロを定義せずともコンパイル出来るようなコードにしてください」ということです。

`strcpy` だけでなく、`strcat` や `_itoa` など `_CRT_SECURE_NO_WARNINGS` を定義しない場合にコンパイルエラーとなる全ての関数を別のものに置き換えてください。

**Comment by mrrsh** [comment]
strcatと_itoaを消して、違う処理に変更しました。課題3,5ともに_CRT_SECURE_NO_WARNINGSマクロを定義しなくてもビルドできています。確認お願いします。

**Comment by kohnakagawa-ffri** [comment]
確認しました。大丈夫です。
最後に出力されるwarningsをすべて消してください。以下のwarningsが表示されます。

```
C4477: 'printf' : 書式文字列 '%s' には、型 'char *' の引数が必要ですが、可変個引数 1 は型 'LPVOID' です
C4267: '=': 'size_t' から 'int' に変換しました。データが失われているかもしれません。
C4778: 'printf' : 書式文字列 '%-*' がありません
C4474: 'printf': 書式文字列に渡された引数の数が多すぎます
```

**Comment by mrrsh** [comment]
対応しました。こちらではwarningsは表示されません。確認お願いします。

**Comment by kohnakagawa-ffri** [comment]
確認しました。クローズします。
