### ISSUE TITLE
[課題1] npathのメモリリーク

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#12]
makeDir関数内npathがfreeされていない分岐がいくつかあります。
ernum == ERROR_ALREADY_EXISTSのときとexitに飛ぶときですね。
exit直前のfreeは議論がありますが、今回の課題ではそこもつけるようにしたいと思います。

ご対応よろしくお願いいたします。

**Comment by mrrsh** [comment]
対応しました。確認お願いします。

**Comment by ffriyukimogi** [comment]
確認しました。OKです。closeします。
