### ISSUE TITLE
[課題4] malloc及びreallocのNULLチェックがない

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#14]
printFiles関数中malloc及びreallocのNULLチェックがほぼありません
またreallocは
```cpp
handleInfo = (PSYSTEM_HANDLE_INFORMATION)realloc(handleInfo, handleInfoSize *= 2);
```
としてはダメで、
```cpp
handleInfoTmp = (PSYSTEM_HANDLE_INFORMATION)realloc(handleInfo, handleInfoSize *= 2);
```
のように一度別の変数に代入しなければなりません
上のコードではreallocが失敗した際、handleInfoの指すオブジェクトが解放されないうちにNULLがhandleInfoに代入されます。handleInfoが指していたオブジェクトにはもうアクセスできません。解放できません。したがって一度別の変数に返り値を格納して、NULLチェックを行った上でhandleInfoに戻す必要があります

**Comment by mrrsh** [comment]
reallocの戻り値先を一時変数へ変更、malloc、reallocのNULLチェックを追加、を行いました。
確認お願いします。

**Comment by ffriyukimogi** [comment]
https://github.com/mrrsh/internship/blob/1a3f138a382884c6fb0ae53cc131ebf42777a7a6/solution/Ex4/handles.c#L266-L276
272行目から276行目までを括弧でくくらないと、handleInfoとhandleInfoSizeは変わらないため終わりません。
またhandleInfoTmpをNULLで初期化していないため、一度もwhileで繰り返さなかった場合よくわからないものがhandleInfoに代入され、そのまま実行されていきます。
handleInfoTmpをNULLで初期化しましょう。

**Comment by mrrsh** [comment]
whileの範囲修正、realloc用の一時変数のNULL初期化を行いました。確認お願いします。

**Comment by ffriyukimogi** [comment]
https://github.com/mrrsh/internship/blob/6d7038dcde53603298d12eafdc7c37146849d1c9/solution/Ex4/handles.c#L246
この書き方はhandleInfoがNULLで初期化されているのか紛らわしいため、handleInfoTmpを初期化する場合は行を分けたほうがリーダブルで良いです

**Comment by mrrsh** [comment]
度々汚いコードを見せてしまいすいません。
一時ファイルのNULL初期化を改行しました。確認お願いします。

**Comment by ffriyukimogi** [comment]
OKです。closeします。
