### ISSUE TITLE
[課題5] std::stringの使用の推奨

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#15]
課題5、C++で書くのであれば文字列にはstd::stringを使ったほうが良いです。
strcatもstrcpyもcallocもいらない、安全で可読性の高いコードになります。

**Comment by mrrsh** [comment]
課題5の文字列操作を全てstringに変更しました。boostを使ったのですが、package全てをpushしようとしたら、サイズ制限で弾かれましたので、必要そうなものだけpushしました。
確認お願いします。

**Comment by ffriyukimogi** [comment]
ビルドできません
mplやpreprocessorが必要なようです
std::stringの使用についてはOKです
boost、使っても良いですが問題なくビルドできる範囲でお願いします

**Comment by mrrsh** [comment]
packageを追加しました。ビルドを始めると足りないものがダウンロードされます。
こちらでは、ビルドが失敗した場合、ヘッダファイルの解析などが始まり、もう一度ビルドをすると成功しました。
boostを使用するつもりはなかったのですが、FILEからstreamへの変換がboostを使用しないやり方が分からなかったため、やむを得なくといった経緯です。
確認お願いします。

**Comment by ffriyukimogi** [comment]
boostを使用しない場合はfgetsで読み込んでstringstreamに流し込めばよいですが、ビルド出来たのでOKです
closeします
