### ISSUE TITLE
[課題5] 範囲for文の使用の推奨

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#16]
```cpp
for (auto itr = pidToproc.begin(); itr != pidToproc.end(); itr++) 
```
より
```cpp
for (auto &e: pidToproc) 
```
として範囲for文を使ったほうがシンプルに書けます(itr->firstやitr->secondがe.firstやe.secondになります)

**Comment by mrrsh** [comment]
対応しました。確認お願いします。

**Comment by ffriyukimogi** [comment]
非常に細かくて申し訳ないのですが、
https://github.com/mrrsh/internship/blob/1a3f138a382884c6fb0ae53cc131ebf42777a7a6/solution/Ex5/union.cpp#L93
のitrはイテレーターではないのでitrという変数名は紛らわしいです。特にitr2がイテレーターのため、
```cpp
for (auto &itr: pidToroc)
{
    /*
    do something...
    */
    itr->first;  //エラー
}
```
と書いてしまう危険性が高いです。valやelemにした方が良いです(本当は一読して変数が指しているものの意味の分かる名前が良いですが、思いつきませんでした)。
また
https://github.com/mrrsh/internship/blob/1a3f138a382884c6fb0ae53cc131ebf42777a7a6/solution/Ex5/union.cpp#L96-L97
にも範囲for文が使えます。例えば
```cpp
for (auto &val : pidTodlls[elem.first])
{
    cout << val;
}
```
のようにより短く書けます。

ちなみにこれは余談ですが、実はC++17であれば構造化束縛を用いて
```cpp
for (auto &[key, elem] : pidToproc)
```
と書けます。これを使うとfirstとsecondも要らなくなります。もし興味と時間があれば調べてみてください。興味はあるけど時間がなければインターン期間中にお教えしますので、今C++17対応まではしなくて大丈夫です

**Comment by mrrsh** [comment]
foreach化、構造化束縛を用いたfor文に修正を行いました。
C++17には興味がありますので、できれば教えてもらいたいです。
確認お願いします。

**Comment by ffriyukimogi** [comment]
OKです。構造化束縛の使い方もOKです。ただ構造化束縛を使うなら
https://github.com/mrrsh/internship/blob/5ed09e21128e0f00704f10a59a3a8dbfc08879e2/solution/Ex5/union.cpp#L137-L146
は
```cpp
    auto [first, end] = pidTocon.equal_range(pid);
    if (first == end)
    {
        cout << "NO CONNECTION\n";
        continue;
    }
    std::for_each(first, end, [](auto &val) {
        cout << val.second << '\n';
    });
```
とやると更に綺麗くらいでしょうか。issueとしてはcloseします。
