### ISSUE TITLE
[課題4] GetfileSecurity関数によるhangの回避のヒント

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#18]
handle64.exeはGetfileSecurity関数を使っていません
GetTokenInformationを使うと良いかもしれません(少なくともhandle64.exeはそれを使っています)

**Comment by mrrsh** [comment]
不勉強で申し訳ないのですが、GetTokenInformationを使用してプロセスのアクセストークンの情報を抜き出してから、どのようにしてファイルに対するパーミッション情報を得ればよいでしょうか。
今の処理では、GetFileSecurityでファイルに対するSDを取得し、そこからDACLを参照してそのアクセス制御を見ているのですが、ファイルのDACLを使用せずに、パーミッション情報を得る方法がよく分かりません。
ヒントでも良いので、できればご助言お願いします。

**Comment by mrrsh** [comment]
管理者権限を使用しなくても実行できるようにしました。こちらはハングせずに実行できていますので、よろしければご確認お願いします。
