### ISSUE TITLE
[課題5] ローカル変数の宣言が早い

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#19]
C++ではローカル変数の宣言を関数の最初で行う必要はありません
必要になったときに宣言したほうが変数のスコープが短くなり、良いです
https://github.com/mrrsh/internship/blob/465580ccc2e836a453f6e0455e2c96bb42a826b0/solution/Ex5/union.cpp#L103
関数の戻り値で初期化できるならそこでautoを使った方が良いです
```cpp
auto file = _popen("netaof2", "r");
```
(例としてここを上げましたが、ここ以外もそうです)
またfor文のインデックスは使い回さず、for (auto i = 0; hogehoge...)としたほうが、やはりインデックスのスコープが短くなるため良いです

**Comment by ffriyukimogi** [comment]
確かにstd::stringやstd::vector、動的変数はループの外で宣言したほうが性能は良くなることが多いです
しかしそれをやるならば関数の最初ではなくループの手前で宣言すべきです

必要になったときに宣言、というのは使う直前で宣言、ということです
変数のスコープは短くできるなら短くすべきです(リーダブルコード9章)
従って例えば
https://github.com/mrrsh/internship/blob/5ed09e21128e0f00704f10a59a3a8dbfc08879e2/solution/Ex5/union.cpp#L40
は
https://github.com/mrrsh/internship/blob/5ed09e21128e0f00704f10a59a3a8dbfc08879e2/solution/Ex5/union.cpp#L50-L52
の直前に書くべきです(他の関数の先頭で宣言されている変数も同様)

**Comment by mrrsh** [comment]
なるほど、分かりました。
変数を使用する直前に移動しました。確認お願いします。

**Comment by ffriyukimogi** [comment]
OKです。closeします。
