### ISSUE TITLE
[課題1] PathRemoveFileSpecWの戻り値のチェックがない

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#3]
mymkdir.cpp26行目でPathRemoveFileSpecWの戻り値をチェックしておりません
戻り値をチェックするか、GetLastErrorでエラーチェックをした方が良いです

**Comment by mrrsh** [comment]
対応しました。
確認お願いします。

**Comment by ffriyukimogi** [comment]
確認いたしました。OKです。closeします。
