### ISSUE TITLE
[課題1] callocの戻り値のチェックがない

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#4]
mymkdir.cppの12行目のcallocの戻り値のチェックがありません
callocはNULLを返すことがあります
その場合、25行目でwcscpyの第一引数にNULLが入ってしまいます
これはwcscpyのSAL注釈と一致しません
callocの戻り値をチェックし、NULLならエラーを表示して終了するといった動作になるようお願いいたします

**Comment by mrrsh** [comment]
対応しました。
確認お願いします。

**Comment by ffriyukimogi** [comment]
確認いたしました。OKです。closeいたします。
