### ISSUE TITLE
[課題3] Debug Error: Stack around the variable 'str' was corrupted

### ISSUE THREAD

**Issue by ffriyukimogi** [mrrsh/internship#5]
環境:Windows 10
再現率:4/4
症状:ソリューション構成Debug x64でビルド後実行する。
結果、 デフォルトゲートウェイまでは一覧が表示されるが、ローカルホストのローカルアドレスが表示された後Debug Error Stack around the variable 'str' was corruptedが出る
期待される動作: Debug Errorが出ない(この場合スタックの破壊が起こらない)

ご対応よろしくお願いいたします

**Comment by mrrsh** [comment]
portjudge内で直接スタック内の変数のアドレスを返していたため、portjudgeの処理が終わった後にスタック破壊が起きていたのではないかと考えられます。引数に渡した変数に文字を格納して返すように処理を変更しました。こちらではエラーが表示されなくなりました。確認お願いします。

**Comment by ffriyukimogi** [comment]
確認しました。OKです。closeします。
