### ISSUE TITLE
(課題3) main関数の行数が長い。

### ISSUE THREAD

**Issue by kohnakagawa-ffri** [mrrsh/internship#8]
https://github.com/mrrsh/internship/blob/969c7f684765a6887b7426e213ddfc3359e90f98/solution/Ex3/netaof.cpp#L58-L217

main関数が長すぎます。TCPとUDPで処理は別々なので、関数として処理を切り出しましょう。

参考: http://www.pro.or.jp/~fuji/mybooks/cdiag/cdiag.1.3.html

**Comment by mrrsh** [comment]
TCPとUDPで関数を分けました。確認お願いします。

**Comment by kohnakagawa-ffri** [comment]
ご対応ありがとうございます。
TCPのIPv6の場合の実行結果が間違っています。(statusがunknownに、ポート番号が3722304989となります。)再度修正をお願いします。

**Comment by mrrsh** [comment]
IPv6のステータスとプロセスIDが、IPv4のテーブルを参照していたため、IPv6のテーブルを参照するように修正しました。
ポート番号が誤った表示になるバグはこちらでは見受けられませんが、portjudge内でport変数をnullで埋める処理を追加しました。修正できていない場合、可能であれば正しいポート番号と実際表示されるポート番号の組を教えていただければ幸いです。

**Comment by kohnakagawa-ffri** [comment]
申し訳ございません。port番号ではなく、`PID` の方でした。失礼しました。
修正が正しく行われていることを確認いたしました。クローズします。
